### ISSUE TITLE
Scrollbars in Liferea, Midori and maybe other webkit2gtk applications are wrongly rendered and leaves artifacts

### ISSUE THREAD

**Issue by Tichy** [tsujan/E17gtk#10]
![liferea](https://cloud.githubusercontent.com/assets/2348771/24562607/93f09c8a-164b-11e7-9e46-af431ac5b736.jpg)

It works but it's rendered half out of place and leaves glitches and trails when moved.

Liferea version 1.12-rc2
midori-0.5.11-5

**Comment by tsujan** [comment]
Since Liferea is based on gtk2, I may know why that happens (like in gtk3 emacs). Will look into it tomorrow.

**Comment by Tichy** [comment]
I tried Midori, which is also using webkit2gtk for the web view and it has the same problem. I think it could be related to all webkit2gtk applications.

**Comment by tsujan** [comment]
Please see if the problem is fixed now (by https://github.com/tsujan/E17gtk/commit/2e7e5fef2c0ff39a81d25621065aca5d616a9ba3).

**Comment by Tichy** [comment]
I tried, but no... The bar is still off-center and the through is different from the theme. :(

**Comment by tsujan** [comment]
Oh, Liferea uses gtk3 here (in Manjaro). What about Midori?

**Comment by Tichy** [comment]
pactree says that's gtk3 also in arch for both liferea and midori. That's also for webkit2gtk

**Comment by tsujan** [comment]
OK. I'm working on it. It seems that webkit doesn't understand negative margins.

**Comment by tsujan** [comment]
Both Liferea and Firefox issues are fixed (here). I had to remove scrollbar steppers for that. Please test and close the issues if they are really fixed. Please also check if ordinary gtk3 apps are OK (although I've checked).

The root of the problem was something general about gtk: gtk is not self-consistent. For example, it has scrollbar steppers but if they're used, they will cause problems like this one. This is just one example of many problems of gtk that made me migrate to Qt years ago. If you use Enlightenment, I recommend you use Qt apps with [Kvantum](https://github.com/tsujan/Kvantum)'s default theme. That's what I do when I work under E.

**Comment by Tichy** [comment]
I confirm that both are fixed. :)
I'm using kvantum for my qt apps (only keepassx) and it's indeed much better, but most of my apllications are gtk based. I need to find some qt alternatives that doesn't need to install kde/plasma/phonon as dependency. Another problem with gtk is that at every update, they break almost all themes.

**Comment by tsujan** [comment]
> I need to find some qt alternatives that doesn't need to install kde/plasma/phonon as dependency

I agree that there are many nice GTK apps but, most of the time, I've found better Qt apps with the same functionalities. This might be of help:

I have three desktop environments: KDE, Enlightenment and LXQt. Under Enlightenment, I mostly use Qt5 apps (Firefox and some other apps are exceptions) but I've set up some environment variables. For example, I've set `QT_QPA_PLATFORMTHEME` to `lxqt`, `QT_STYLE_OVERRIDE` to `kvantum` and `BROWSER` to `qupzilla`. I've also added `lxqt-policykit-agent` to the startup apps. For the file manager, pcmanfm-qt is OK but recently I prefer Dolphin over it. For terminal, Terminology is excellent but QTerminal is OK too; etc.

**Comment by Tichy** [comment]
I'm using qt5ct to manage qt5 themes. I had to set QT_QPA_PLATFORMTHEME to qt5ct and unset QT_STYLE_OVERRIDE to make it work. I'm now trying PCManFM-qt instead of Thunar, KVIrc (which I used years ago) instead of Hexchat and qBittorrent instead of Transmission (and that's a big improvement, since qBittorrent is way better). I'll try some more QT alternatives, hoping to find some that don't have too many dependency on kde libs... Or I'll switch directly to kde applications so that those libs aren't installed only for few apps, but many :D

**Comment by tsujan** [comment]
> I'm using qt5ct to manage qt5 themes.

Yes, it's a good plugin too. `lxqt` for `QT_QPA_PLATFORMTHEME` is a little more standard and advanced.

> I'll try some more QT alternatives, hoping to find some that don't have too many dependency on kde libs

I agree that kde dependencies aren't so good when KDE isn't installed. Fortunately, there's a tendency toward KDE-independent Qt apps nowadays.
