### ISSUE TITLE
Gucharmap: character table with white on white characters

### ISSUE THREAD

**Issue by Tichy** [tsujan/E17gtk#11]
![shot-2017-04-01_12-22-15](https://cloud.githubusercontent.com/assets/2348771/24577859/6aac3b00-16d6-11e7-9cdd-c0e2542266fd.jpg)

This is from the gtk3 application gucharmap. The characters table is rendered with white text on white background, except when a character is selected.

**Comment by tsujan** [comment]
It should be fixed now. gucharmap uses fallback color for those cells!! Previously it didn't. I think that's due to a gtk change and the old code of gucharmap.

Thanks for reporting!

Apparently most gtk theme makers copy the latest Adwaita and then change it. I try to follow logic instead but it seems there's no logic here ;)

**Comment by Tichy** [comment]
Fixed also here. Thanks. :)
Yeah... I don't like how gtk is now. Gnome-centric. I don't like how most gtk themes are, mostly flat, bright and barely distinguishable from each other. I even don't like that client side decorations which you can't disable... It's silly that you can't even close or move an application that's struck, because it's the application itself that manage its windows controls.
So, I came back to E perhaps as a reaction to all this, after a long period with tiling wms and terminal applications.
Your theme for E is, imho, a must. Before it was ported to a recent gtk3 version I used Vertex, which fits quite well anyway, but not so well.
...end of rant :D

**Comment by tsujan** [comment]
> So, I came back to E perhaps as a reaction to all this

Interesting! I wouldn't discover E if it weren't for disastrous changes in Gnome3 :) I use E for fun; it feels "cozy" once it's set up correctly.
