### ISSUE TITLE
Release for Gtk+-3.24

### ISSUE THREAD

**Issue by romildo** [tsujan/E17gtk#12]
My understanding is that `E17gtk` currently is adapted to `Gtk+-3.22`, right? Now that `Gtk+-3.22` is gone from some Linux distributions it would be a nice idea to get `E17gtk` adapted for `Gtk+-3.24`.

**Comment by vcunat** [comment]
It's a bit confusing, but there's no gtk+ 3.24 and we're still keeping 3.22.x in nixpkgs.  They are changing the approach for releases, but I don't remember details.  Here's what's available: https://download.gnome.org/sources/gtk+/

**Comment by romildo** [comment]
It seems then that `gnome3` and `gtk3` does not have parallel versions any more.

**Comment by tsujan** [comment]
After a stable gtk-3.24 comes out, I'll make the necessary changes if I find some free time. Generally, I try to keep this theme up-to-date; it's just a matter of free time.

And no, the version of gnome3 isn't that of gtk3. gtk-3.22 is the latest stable version for now.

**Comment by tsujan** [comment]
BTW, the next stable gtk will come to Arch first and, after a week or two, to Manjaro Testing (my distro).

**Comment by vcunat** [comment]
If I understand it correctly, the plans are still that the next *stable* branch after 3.22 will be 4: https://blog.gtk.org/2016/09/01/versioning-and-long-term-stability-promise-in-gtk/
