### ISSUE TITLE
Firefox sidebar needs abit more contrast.

### ISSUE THREAD

**Issue by ispanos** [tsujan/E17gtk#15]
I read on one of the closed issues that you had #ECECEC as a default for a very long time, but in this case the text is almost unreadable. Is there a workaround for that?
I did create  the '~/.mozilla/firefox/<MY_PROFILE>/chrome/userContent.css' file, like described in  the workaround doc.
![2019-01-22-04 46 45](https://user-images.githubusercontent.com/42875202/51509261-0ccbe380-1e01-11e9-84a2-dfc5395293a4.png)

**Comment by tsujan** [comment]
Firefox has changed a lot and I haven't had such problems with it for a while. Don't apply any stylesheet but wait for a fixed version of it. This is 64.0.2:

![firefox](https://user-images.githubusercontent.com/981076/51550858-848e2280-1e82-11e9-8377-83c6eaf79373.png)

**Comment by ispanos** [comment]
I see, you are using the dark theme, which looks great. I am using the default theme. 
The default theme has a grey color on the tab "bar" which fits in better with the overall grey theme I have, but the dark theme uses a dark grey "background" color on the side bar.  I don't consider the issue "solved", but many people use the dark theme so its not a huge deal. I do have Firefox 64.0.2.

Thanks anyway.

**Comment by tsujan** [comment]
> I see, you are using the dark theme

I didn't touch anything.

Anyway, these problems are definitely in Firefox, which has had so many of them for so many years.

**Comment by ispanos** [comment]
> dark theme

By dark theme I mean the firefox theme in the "customize... " section.

**Comment by tsujan** [comment]
> By dark theme I mean the firefox theme in the "customize... " section.

I have this:

![custom](https://user-images.githubusercontent.com/981076/51553952-59f39800-1e89-11e9-9f1b-129410b6b696.png)

As I said, I didn't change anything. It seems Manjaro's defaults are good.

**Comment by ispanos** [comment]
> It seems Manjaro's defaults are good.

Yeah, maybe they changed the default theme. I use manjaro too, but with everything un-configured. Maybe I'll try to change the default background color in the sidebar myself.

**Comment by tsujan** [comment]
BTW, I tested the default gtk theme and couldn't tolerate it with a few gtk apps I had. Will try to maintain E17gtk in my free time.

**Comment by ispanos** [comment]
> couldn't tolerate it with a few gtk apps

I only have gtk apps installed atm and I can't stand it for any of them. In libreoffice especially its hideous. I only have 11 packages that  have a GUI,  and 7 of them are gtk only. I would like to find qt alternatives at some point and try qt only if  I can.
