### ISSUE TITLE
Gtk 3.24

### ISSUE THREAD

**Issue by nift4** [tsujan/E17gtk#16]
I noticed nothing is happening here but I still hope an release for Gtk 3.24 will come :)

**Comment by nift4** [comment]
I installed the theme anyway and noticed the Ubuntu System Update application is missing the small arrow to expand the details section

**Comment by tsujan** [comment]
> I still hope an release for Gtk 3.24 will come

I have GTK 3.24.20 and the theme is OK.

The theme is for a few GTK apps I have and I only check `gtk3-widget-factory` to see if it needs a change.

**Comment by nift4** [comment]
Nice :)
As I said, the small arrow was missing/invisible

**Comment by tsujan** [comment]
> As I said, the small arrow was missing/invisible

As I said, "... I only check `gtk3-widget-factory`..."

**Comment by nift4** [comment]
ok
