### ISSUE TITLE
Menu and tool bar in Evolution 3.18 are messed up

### ISSUE THREAD

**Issue by mbert** [tsujan/E17gtk#2]
I'm using RHEL 7 with Evolution 3.18 and gnome desktop 3.14. In Evolution menu bar and toolbar are messed up to a state where they are just not usable. See the screenshot:
![screenshot-2016-11-11-09 59 47](https://cloud.githubusercontent.com/assets/383271/20209646/c60a840c-a7f5-11e6-954d-99e1be49513f.png)

**Comment by tsujan** [comment]
The latest version of E17gtk is for gtk-3.22 and GTK+-3 lacks backward compatibility. I made this GitHub page after gtk-3.20 so, unfortunately, E17gtk can't be used with previous versions of GTK+-3.
