### ISSUE TITLE
Hard to read tools menu in Firefox

### ISSUE THREAD

**Issue by Tichy** [tsujan/E17gtk#4]
![shot-2017-03-25_19-43-13](https://cloud.githubusercontent.com/assets/2348771/24325199/f59780be-1193-11e7-8da4-ef0c37cdc3d1.png)

The background is too bright making it hard to read.
All the other menus are fine.

**Comment by tsujan** [comment]
OK. This is like https://github.com/tsujan/E17gtk/issues/3. It seems that non-gtk3 apps that use gtk3 style don't support all the flexibility of gtk3. I'll change the view color soon,

**Comment by tsujan** [comment]
Problem fixed. Please use the latest github version!

**Comment by Tichy** [comment]
Everything's right, now. 😄

**Comment by tsujan** [comment]
Thanks for testing! Closing this.
