### ISSUE TITLE
Menu gradient shouldn't be proportional to menu size (including fix)

### ISSUE THREAD

**Issue by Tichy** [tsujan/E17gtk#6]
Before the fix (the left menu is taller and has a longer gradient)
![2017-03-26-031416_2560x1440_scrot](https://cloud.githubusercontent.com/assets/2348771/24327505/64bc992c-11d3-11e7-896b-8821df82fb40.png)

After (the left menu now has a gradient the same size of other menus)
![2017-03-26-031341_2560x1440_scrot](https://cloud.githubusercontent.com/assets/2348771/24327503/5d3eea06-11d3-11e7-8860-5527d0349c94.png) 

For gtk2 change the border to include the top and bottom gradients (I have also shrinked the other borders which don't need to be 8 pixels)
```
style "menu"
{
	bg[NORMAL]   = shade (0.9, @bg_active_color)
	fg[NORMAL]   = "#ffffff"
	text[NORMAL] = "#ffffff"

	engine "pixmap" # just for similarity to the GTK3 theme
	{
		image
		{
			function	= BOX
			detail		= "menu"
			file		= "assets/menu.png"
			border		= {4,4,11,4}
			stretch		= TRUE
		}
	}
}
```

For gtk3 change the second gradient color size from 6% to a fixed 11 pixels (same as in gtk2)
```
menuitem menu {
	background-color: shade(@theme_selected_bg_color, 0.8);
	background-image: linear-gradient(to bottom,
	                                  shade(@theme_bg_color, 1.5),
	                                  @theme_bg_color 11px,
	                                  @theme_bg_color);

	border-style: none;
	border-width: 0px 1px 1px 1px;
	border-radius: 0;
	padding: 1px;
}
```

**Comment by tsujan** [comment]
Thanks for your attention! You're right.

E17gtk needs to be improved. Since 90% of my apps are Qt based and 99.9% of my dev work is related to C++ and Qt, I may not notice some problems. So, good reports like this one would be really appreciated.

A few minutes ago, I fixed some issues in E17gtk. Tomorrow, I'll fix the menu gradient.
