### ISSUE TITLE
Firefox scrollbar badly rendered

### ISSUE THREAD

**Issue by Tichy** [tsujan/E17gtk#9]
![firefox](https://cloud.githubusercontent.com/assets/2348771/24562452/25da78f6-164b-11e7-85df-55d18f2b55e2.jpg)

See screenshot. :)
Beside its appearance, it works ok and doesn't leave trails or glitches.

Firefox 52.0.2

**Comment by tsujan** [comment]
Here, it's just wider that usual.

EDIT: ... and borderless.

**Comment by Tichy** [comment]
Yes, also it has different borders and "external" (I mean out of the handle) background.

**Comment by Tichy** [comment]
Fixed with the last commit. Closing.
